### ISSUE TITLE
UE 4.27 Two Participants in the scene crash

### ISSUE THREAD

**Issue by Gata-chan** [Mountea-Framework/MounteaDialogueSystem#11]
**Describe the bug**
Preamble: I know that you are abandoning 4.27 version of UE and that's fair, I am not expecting you to fix this but maybe just help me in this problem.

So, the UE Consistently crashes when I try to boot up a scene from the editor. It gives me this as a crahs report:

<details><summary>Details</summary>
<p>

`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UE4Editor_MounteaDialogueSystem!UMounteaDialogueDecorator_OnlyFirstTime::InitializeDecorator_Implementation() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MounteaDialogueSystem\Source\MounteaDialogueSystem\Private\Decorators\MounteaDialogueDecorator_OnlyFirstTime.cpp:17]
UE4Editor_MounteaDialogueSystem!UMounteaDialogueDecoratorBase::execInitializeDecorator() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MounteaDialogueSystem\Intermediate\Build\Win64\UE4Editor\Inc\MounteaDialogueSystem\MounteaDialogueDecoratorBase.gen.cpp:254]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_MounteaDialogueSystem!UMounteaDialogueDecoratorBase::InitializeDecorator() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MounteaDialogueSystem\Intermediate\Build\Win64\UE4Editor\Inc\MounteaDialogueSystem\MounteaDialogueDecoratorBase.gen.cpp:293]
UE4Editor_MounteaDialogueSystem!UMounteaDialogueParticipant::InitializeParticipant_Implementation() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MounteaDialogueSystem\Source\MounteaDialogueSystem\Private\Components\MounteaDialogueParticipant.cpp:43]
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll`

</p>
</details> 

**To Reproduce**
Have 1 Actor (Player Pawn) Dialogue Manager and Dialogue Participant BPs then...

1. Go to another Actor
2. Add the Dialogue Participant BP to them
3. Try to boot up the scene from the Editor
4. Experience Immediate Crash

**Expected behavior**
I expected to load into the scene without crashing

**Desktop:**
 - OS: Windows 10
 - Version Unreal Engine 4.27.2

**Comment by pavlicekdominik** [comment]
Fixed in 5.x onwards
